### PR TITLE
Update logo to new vector graphics

### LINKED ISSUE #50: Update logo to new vector graphics
With the creation of the new branding and logo earlier this year, the logo has been updated to a new design. This new logo has been recreated using vector graphics as well. The logo needs to be updated in the favicon and the top of the page in the HTML template.

### PR DESCRIPTION
**Pull request by jerrettl**
Updated the top horizontal page logo and favicon with new logo assets. Tested new appearance changes on Chromium and Firefox.

Closes #50.

### CODE REVIEW

**Comment by panbed** [comment]
Logo looks freaking awesomesauce, I think the only (maybe, if it's even worth it) change I'd make is maybe add a small drop shadow to the favicon? It looks fine on dark themes, but I just opened Edge with a light theme and it's a little hard to distinguish against the background, especially in the second example where it's not the highlighted tab:
image

I'm not the greatest at making icons, but I made a mock up and it's a little better I _guess_ with a small drop shadow.
image

**Comment by jerrettl** [comment]
Ah good point! The little icon is only 48x48 pixels, but I'll go in and tweak it soon to see what I can do with our assets.

**Comment by jerrettl** [comment]
Icon has been updated! I am done fighting with Adobe Illustrator

**Review by panbed — APPROVED** [review]
Everything looks good, I think this is ready to merge lol

**Pull request merged**
